spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddd
    username: root
    password: password
    hikari:
      maximum-pool-size: 10

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
